services:
  - type: web
    name: stockapp-dash
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT --workers 1 --threads 4 --worker-class gthread --timeout 120
    envVars:
      - key: GH_PAT
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_SESSION
        sync: false
